### ISSUE TITLE
live doesn't work. I tested it on my own Youtube channel

### ISSUE THREAD

**Issue by MartijnKaijser** [enen92/plugin.video.kordkutters#2]

**Comment by MartijnKaijser** [comment]
nevermind, just took a long while. 
Guess we should shove it in repo now?

**Comment by enen92** [comment]
Yeah live stuff can take a while to load but I just send the video id to youtube addon. I'll still need to fix/add a few things tonight and maybe its ready tomorrow. Hopefully before the show :)

**Comment by MartijnKaijser** [comment]
do note it will take some time before i can push it to the server and then it still has to be distributed and synced to all kodi installs for it to show up ;)

edit:
imo if it works ok already just send it to repo and fixup the rest later

**Comment by enen92** [comment]
Hum seems ok to me. I will just add a missing thumb and then submit it to repository. The commit is identified in the email so I assume I can still continue to work and commit to master right?

**Comment by MartijnKaijser** [comment]
just bump the version number so people who had it installed manual will get the update. 
Yes we pick the referenced commit and can keep working in master

**Comment by enen92** [comment]
Done and submited
Regards
