### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by enen92** [enen92/plugin.video.kordkutters#3]
- Treat playlists as tvshows and not as files
- Option to save view type in context menu item and setviewmode

**Comment by Goofer3** [comment]
hello

Not sure if this is where I am supposed to leave a message but here it goes...new to the fire stick and would love to add WSL to it...it won't work directly from my laptop only from TV so can I get the link/URL for the zip file so I can put it in my root and load it from there?

**Comment by enen92** [comment]
The plugin is in kodi official repository you should install it from there:

http://kodi.wiki/view/add-on_manager

**Comment by Goofer3** [comment]
Thank you I did that and it is my root but how do I watch WSL now?

Sent from Yahoo Mail on Android 

  On Tue, Jul 12, 2016 at 10:59 AM, enen92notifications@github.com wrote:  
The plugin is in kodi official repository you should install it from there:

http://kodi.wiki/view/add-on_manager

**Comment by enen92** [comment]
No idea what WSL is...
This addon is for Kordkutters, a podcast dedicated to Kodi.

**Comment by Goofer3** [comment]
Sorry to be such a pain...WSL is World Surf League...trying lo load to my stick into/through kodi but can't seem to figure it out.

Sent from Yahoo Mail on Android 

  On Tue, Jul 12, 2016 at 3:03 PM, enen92notifications@github.com wrote:  
No idea what WSL is...
This addon is for Kordkutters, a podcast dedicated to Kodi.
