### ISSUE TITLE
I doubt Nate and Ned speak Portuguese ;) At least not last time in Lisbon

### ISSUE THREAD

**Issue by MartijnKaijser** [enen92/plugin.video.kordkutters#4]
https://github.com/enen92/plugin.video.kordkutters/blob/master/addon.xml#L10

already fixed it on repo version

**Comment by enen92** [comment]
ah crap I adapted it from the rtp play addon and forgot that. Finally understood what the hell is going on in the repo lol

**Comment by MartijnKaijser** [comment]
Well plugin repo is another story ;) 
Was server issue
