### ISSUE TITLE
using deprecated way of calling Youtube addon

### ISSUE THREAD

**Issue by MartijnKaijser** [enen92/plugin.video.kordkutters#8]
21:42:10 T:11256 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?path=/root/video&action=play_video&videoid=9vCllSWxzeI"
21:42:10 T:11256 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=9vCllSWxzeI"

**Comment by enen92** [comment]
Tks
